# Generated by Django 4.0.4 on 2022-05-19 21:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petition', '0002_remove_petitionnotification_petition_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PetitionNotification',
            new_name='Notification',
        ),
    ]
