# Generated by Django 4.0.4 on 2022-05-20 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petition', '0003_rename_petitionnotification_notification'),
    ]

    operations = [
        # STATE MIGRATION ONLY
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at',), 'verbose_name': 'Petition News', 'verbose_name_plural': 'Petition News'},
        ),
        migrations.AddField(
            model_name='petition',
            name='signatories',
            field=models.ManyToManyField(related_name='signed_petitions', through='petition.Vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='petition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='petition.petition', verbose_name='Petition'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
