# Generated by Django 4.0.4 on 2022-05-20 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0004_alter_notification_options_petition_signatories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petition',
            old_name='votes_cache',
            new_name='signatories_count',
        ),
    ]
